<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateCountryMaster extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('country_master', function (Blueprint $table) {
            $table->id()->comment('Serial ID');
            $table->string('country_name')->comment('Country Name');
            $table->string('country_code', 5)->comment('Country Code');
            $table->tinyInteger('status')->default(1)->nullable()->comment('Status: 0=Inactive, 1=Active');
            $table->dateTime('created_at')->nullable()->useCurrent()->comment('Created Date');
            $table->dateTime('updated_at')->nullable()->default(DB::raw('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))->comment('Modified Date');
            $table->index('country_code');
            $table->index('status');
        });

        // inserting few records
        $insert_data = array(
            array('country_name' => 'Afghanistan', 'country_code' => 'AF', 'status' => 1),
            array('country_name' => 'Albania', 'country_code' => 'AL', 'status' => 1),
            array('country_name' => 'Algeria', 'country_code' => 'DZ', 'status' => 1),
            array('country_name' => 'Andorra', 'country_code' => 'AD', 'status' => 1),
            array('country_name' => 'Angola', 'country_code' => 'AO', 'status' => 1),
            array('country_name' => 'Antigua and Barbuda', 'country_code' => 'AG', 'status' => 1),
            array('country_name' => 'Argentina', 'country_code' => 'AR', 'status' => 1),
            array('country_name' => 'Armenia', 'country_code' => 'AM', 'status' => 1),
            array('country_name' => 'Australia', 'country_code' => 'AU', 'status' => 1),
            array('country_name' => 'Austria', 'country_code' => 'AT', 'status' => 1),
            array('country_name' => 'Azerbaijan', 'country_code' => 'AZ', 'status' => 1),
            array('country_name' => 'Bahamas', 'country_code' => 'BS', 'status' => 1),
            array('country_name' => 'Bahrain', 'country_code' => 'BH', 'status' => 1),
            array('country_name' => 'Bangladesh', 'country_code' => 'BD', 'status' => 1),
            array('country_name' => 'Barbados', 'country_code' => 'BB', 'status' => 1),
            array('country_name' => 'Belarus', 'country_code' => 'BY', 'status' => 1),
            array('country_name' => 'Belgium', 'country_code' => 'BE', 'status' => 1),
            array('country_name' => 'Belize', 'country_code' => 'BZ', 'status' => 1),
            array('country_name' => 'Benin', 'country_code' => 'BJ', 'status' => 1),
            array('country_name' => 'Bhutan', 'country_code' => 'BT', 'status' => 1),
            array('country_name' => 'Bolivia (Plurinational State of)', 'country_code' => 'BO', 'status' => 1),
            array('country_name' => 'Bosnia and Herzegovina', 'country_code' => 'BA', 'status' => 1),
            array('country_name' => 'Botswana', 'country_code' => 'BW', 'status' => 1),
            array('country_name' => 'Brazil', 'country_code' => 'BR', 'status' => 1),
            array('country_name' => 'Brunei Darussalam', 'country_code' => 'BN', 'status' => 1),
            array('country_name' => 'Bulgaria', 'country_code' => 'BG', 'status' => 1),
            array('country_name' => 'Burkina Faso', 'country_code' => 'BF', 'status' => 1),
            array('country_name' => 'Burundi', 'country_code' => 'BI', 'status' => 1),
            array('country_name' => 'Cabo Verde', 'country_code' => 'CV', 'status' => 1),
            array('country_name' => 'Cambodia', 'country_code' => 'KH', 'status' => 1),
            array('country_name' => 'Cameroon', 'country_code' => 'CM', 'status' => 1),
            array('country_name' => 'Canada', 'country_code' => 'CA', 'status' => 1),
            array('country_name' => 'Central African Republic', 'country_code' => 'CF', 'status' => 1),
            array('country_name' => 'Chad', 'country_code' => 'TD', 'status' => 1),
            array('country_name' => 'Chile', 'country_code' => 'CL', 'status' => 1),
            array('country_name' => 'China', 'country_code' => 'CN', 'status' => 1),
            array('country_name' => 'Colombia', 'country_code' => 'CO', 'status' => 1),
            array('country_name' => 'Comoros', 'country_code' => 'KM', 'status' => 1),
            array('country_name' => 'Congo', 'country_code' => 'CG', 'status' => 1),
            array('country_name' => 'Cook Islands', 'country_code' => 'CK', 'status' => 1),
            array('country_name' => 'Costa Rica', 'country_code' => 'CR', 'status' => 1),
            array('country_name' => 'Croatia', 'country_code' => 'HR', 'status' => 1),
            array('country_name' => 'Cuba', 'country_code' => 'CU', 'status' => 1),
            array('country_name' => 'Cyprus', 'country_code' => 'CY', 'status' => 1),
            array('country_name' => 'Czechia', 'country_code' => 'CZ', 'status' => 1),
            array('country_name' => 'Cote dIvoire', 'country_code' => 'CI', 'status' => 1),
            array('country_name' => 'Democratic Peoples Republic of Korea', 'country_code' => 'KP', 'status' => 1),
            array('country_name' => 'Democratic Republic of the Congo', 'country_code' => 'CD', 'status' => 1),
            array('country_name' => 'Denmark', 'country_code' => 'DK', 'status' => 1),
            array('country_name' => 'Djibouti', 'country_code' => 'DJ', 'status' => 1),
            array('country_name' => 'Dominica', 'country_code' => 'DM', 'status' => 1),
            array('country_name' => 'Dominican Republic', 'country_code' => 'DO', 'status' => 1),
            array('country_name' => 'Ecuador', 'country_code' => 'EC', 'status' => 1),
            array('country_name' => 'Egypt', 'country_code' => 'EG', 'status' => 1),
            array('country_name' => 'El Salvador', 'country_code' => 'SV', 'status' => 1),
            array('country_name' => 'Equatorial Guinea', 'country_code' => 'GQ', 'status' => 1),
            array('country_name' => 'Eritrea', 'country_code' => 'ER', 'status' => 1),
            array('country_name' => 'Estonia', 'country_code' => 'EE', 'status' => 1),
            array('country_name' => 'Eswatini', 'country_code' => 'SZ', 'status' => 1),
            array('country_name' => 'Ethiopia', 'country_code' => 'ET', 'status' => 1),
            array('country_name' => 'Faroe Islands', 'country_code' => 'FO', 'status' => 1),
            array('country_name' => 'Fiji', 'country_code' => 'FJ', 'status' => 1),
            array('country_name' => 'Finland', 'country_code' => 'FI', 'status' => 1),
            array('country_name' => 'France', 'country_code' => 'FR', 'status' => 1),
            array('country_name' => 'Gabon', 'country_code' => 'GA', 'status' => 1),
            array('country_name' => 'Gambia', 'country_code' => 'GM', 'status' => 1),
            array('country_name' => 'Georgia', 'country_code' => 'GE', 'status' => 1),
            array('country_name' => 'Germany', 'country_code' => 'DE', 'status' => 1),
            array('country_name' => 'Ghana', 'country_code' => 'GH', 'status' => 1),
            array('country_name' => 'Greece', 'country_code' => 'GR', 'status' => 1),
            array('country_name' => 'Grenada', 'country_code' => 'GD', 'status' => 1),
            array('country_name' => 'Guatemala', 'country_code' => 'GT', 'status' => 1),
            array('country_name' => 'Guinea', 'country_code' => 'GN', 'status' => 1),
            array('country_name' => 'Guinea-Bissau', 'country_code' => 'GW', 'status' => 1),
            array('country_name' => 'Guyana', 'country_code' => 'GY', 'status' => 1),
            array('country_name' => 'Haiti', 'country_code' => 'HT', 'status' => 1),
            array('country_name' => 'Honduras', 'country_code' => 'HN', 'status' => 1),
            array('country_name' => 'Hungary', 'country_code' => 'HU', 'status' => 1),
            array('country_name' => 'Iceland', 'country_code' => 'IS', 'status' => 1),
            array('country_name' => 'India', 'country_code' => 'IN', 'status' => 1),
            array('country_name' => 'Indonesia', 'country_code' => 'ID', 'status' => 1),
            array('country_name' => 'Iran (Islamic Republic of)', 'country_code' => 'IR', 'status' => 1),
            array('country_name' => 'Iraq', 'country_code' => 'IQ', 'status' => 1),
            array('country_name' => 'Ireland', 'country_code' => 'IE', 'status' => 1),
            array('country_name' => 'Israel', 'country_code' => 'IL', 'status' => 1),
            array('country_name' => 'Italy', 'country_code' => 'IT', 'status' => 1),
            array('country_name' => 'Jamaica', 'country_code' => 'JM', 'status' => 1),
            array('country_name' => 'Japan', 'country_code' => 'JP', 'status' => 1),
            array('country_name' => 'Jordan', 'country_code' => 'JO', 'status' => 1),
            array('country_name' => 'Kazakhstan', 'country_code' => 'KZ', 'status' => 1),
            array('country_name' => 'Kenya', 'country_code' => 'KE', 'status' => 1),
            array('country_name' => 'Kiribati', 'country_code' => 'KI', 'status' => 1),
            array('country_name' => 'Kuwait', 'country_code' => 'KW', 'status' => 1),
            array('country_name' => 'Kyrgyzstan', 'country_code' => 'KG', 'status' => 1),
            array('country_name' => 'Lao Peoples Democratic Republic', 'country_code' => 'LA', 'status' => 1),
            array('country_name' => 'Latvia', 'country_code' => 'LV', 'status' => 1),
            array('country_name' => 'Lebanon', 'country_code' => 'LB', 'status' => 1),
            array('country_name' => 'Lesotho', 'country_code' => 'LS', 'status' => 1),
            array('country_name' => 'Liberia', 'country_code' => 'LR', 'status' => 1),
            array('country_name' => 'Libya', 'country_code' => 'LY', 'status' => 1),
            array('country_name' => 'Lithuania', 'country_code' => 'LT', 'status' => 1),
            array('country_name' => 'Luxembourg', 'country_code' => 'LU', 'status' => 1),
            array('country_name' => 'Madagascar', 'country_code' => 'MG', 'status' => 1),
            array('country_name' => 'Malawi', 'country_code' => 'MW', 'status' => 1),
            array('country_name' => 'Malaysia', 'country_code' => 'MY', 'status' => 1),
            array('country_name' => 'Maldives', 'country_code' => 'MV', 'status' => 1),
            array('country_name' => 'Mali', 'country_code' => 'ML', 'status' => 1),
            array('country_name' => 'Malta', 'country_code' => 'MT', 'status' => 1),
            array('country_name' => 'Marshall Islands', 'country_code' => 'MH', 'status' => 1),
            array('country_name' => 'Mauritania', 'country_code' => 'MR', 'status' => 1),
            array('country_name' => 'Mauritius', 'country_code' => 'MU', 'status' => 1),
            array('country_name' => 'Mexico', 'country_code' => 'MX', 'status' => 1),
            array('country_name' => 'Micronesia (Federated States of)', 'country_code' => 'FM', 'status' => 1),
            array('country_name' => 'Monaco', 'country_code' => 'MC', 'status' => 1),
            array('country_name' => 'Mongolia', 'country_code' => 'MN', 'status' => 1),
            array('country_name' => 'Montenegro', 'country_code' => 'ME', 'status' => 1),
            array('country_name' => 'Morocco', 'country_code' => 'MA', 'status' => 1),
            array('country_name' => 'Mozambique', 'country_code' => 'MZ', 'status' => 1),
            array('country_name' => 'Myanmar', 'country_code' => 'MM', 'status' => 1),
            array('country_name' => 'Namibia', 'country_code' => 'NA', 'status' => 1),
            array('country_name' => 'Nauru', 'country_code' => 'NR', 'status' => 1),
            array('country_name' => 'Nepal', 'country_code' => 'NP', 'status' => 1),
            array('country_name' => 'Netherlands', 'country_code' => 'NL', 'status' => 1),
            array('country_name' => 'New Zealand', 'country_code' => 'NZ', 'status' => 1),
            array('country_name' => 'Nicaragua', 'country_code' => 'NI', 'status' => 1),
            array('country_name' => 'Niger', 'country_code' => 'NE', 'status' => 1),
            array('country_name' => 'Nigeria', 'country_code' => 'NG', 'status' => 1),
            array('country_name' => 'Niue', 'country_code' => 'NU', 'status' => 1),
            array('country_name' => 'North Macedonia', 'country_code' => 'MK', 'status' => 1),
            array('country_name' => 'Norway', 'country_code' => 'NO', 'status' => 1),
            array('country_name' => 'Oman', 'country_code' => 'OM', 'status' => 1),
            array('country_name' => 'Pakistan', 'country_code' => 'PK', 'status' => 1),
            array('country_name' => 'Palau', 'country_code' => 'PW', 'status' => 1),
            array('country_name' => 'Panama', 'country_code' => 'PA', 'status' => 1),
            array('country_name' => 'Papua New Guinea', 'country_code' => 'PG', 'status' => 1),
            array('country_name' => 'Paraguay', 'country_code' => 'PY', 'status' => 1),
            array('country_name' => 'Peru', 'country_code' => 'PE', 'status' => 1),
            array('country_name' => 'Philippines', 'country_code' => 'PH', 'status' => 1),
            array('country_name' => 'Poland', 'country_code' => 'PL', 'status' => 1),
            array('country_name' => 'Portugal', 'country_code' => 'PT', 'status' => 1),
            array('country_name' => 'Qatar', 'country_code' => 'QA', 'status' => 1),
            array('country_name' => 'Republic of Korea', 'country_code' => 'KR', 'status' => 1),
            array('country_name' => 'Republic of Moldova', 'country_code' => 'MD', 'status' => 1),
            array('country_name' => 'Romania', 'country_code' => 'RO', 'status' => 1),
            array('country_name' => 'Russian Federation', 'country_code' => 'RU', 'status' => 1),
            array('country_name' => 'Rwanda', 'country_code' => 'RW', 'status' => 1),
            array('country_name' => 'Saint Kitts and Nevis', 'country_code' => 'KN', 'status' => 1),
            array('country_name' => 'Saint Lucia', 'country_code' => 'LC', 'status' => 1),
            array('country_name' => 'Saint Vincent and the Grenadines', 'country_code' => 'VC', 'status' => 1),
            array('country_name' => 'Samoa', 'country_code' => 'WS', 'status' => 1),
            array('country_name' => 'San Marino', 'country_code' => 'SM', 'status' => 1),
            array('country_name' => 'Sao Tome and Principe', 'country_code' => 'ST', 'status' => 1),
            array('country_name' => 'Saudi Arabia', 'country_code' => 'SA', 'status' => 1),
            array('country_name' => 'Senegal', 'country_code' => 'SN', 'status' => 1),
            array('country_name' => 'Serbia', 'country_code' => 'RS', 'status' => 1),
            array('country_name' => 'Seychelles', 'country_code' => 'SC', 'status' => 1),
            array('country_name' => 'Sierra Leone', 'country_code' => 'SL', 'status' => 1),
            array('country_name' => 'Singapore', 'country_code' => 'SG', 'status' => 1),
            array('country_name' => 'Slovakia', 'country_code' => 'SK', 'status' => 1),
            array('country_name' => 'Slovenia', 'country_code' => 'SI', 'status' => 1),
            array('country_name' => 'Solomon Islands', 'country_code' => 'SB', 'status' => 1),
            array('country_name' => 'Somalia', 'country_code' => 'SO', 'status' => 1),
            array('country_name' => 'South Africa', 'country_code' => 'ZA', 'status' => 1),
            array('country_name' => 'South Sudan', 'country_code' => 'SS', 'status' => 1),
            array('country_name' => 'Spain', 'country_code' => 'ES', 'status' => 1),
            array('country_name' => 'Sri Lanka', 'country_code' => 'LK', 'status' => 1),
            array('country_name' => 'Sudan', 'country_code' => 'SD', 'status' => 1),
            array('country_name' => 'Suriname', 'country_code' => 'SR', 'status' => 1),
            array('country_name' => 'Sweden', 'country_code' => 'SE', 'status' => 1),
            array('country_name' => 'Switzerland', 'country_code' => 'CH', 'status' => 1),
            array('country_name' => 'Syrian Arab Republic', 'country_code' => 'SY', 'status' => 1),
            array('country_name' => 'Tajikistan', 'country_code' => 'TJ', 'status' => 1),
            array('country_name' => 'Thailand', 'country_code' => 'TH', 'status' => 1),
            array('country_name' => 'Timor-Leste', 'country_code' => 'TL', 'status' => 1),
            array('country_name' => 'Togo', 'country_code' => 'TG', 'status' => 1),
            array('country_name' => 'Tokelau', 'country_code' => 'TK', 'status' => 1),
            array('country_name' => 'Tonga', 'country_code' => 'TO', 'status' => 1),
            array('country_name' => 'Trinidad and Tobago', 'country_code' => 'TT', 'status' => 1),
            array('country_name' => 'Tunisia', 'country_code' => 'TN', 'status' => 1),
            array('country_name' => 'Turkey', 'country_code' => 'TR', 'status' => 1),
            array('country_name' => 'Turkmenistan', 'country_code' => 'TM', 'status' => 1),
            array('country_name' => 'Tuvalu', 'country_code' => 'TV', 'status' => 1),
            array('country_name' => 'Uganda', 'country_code' => 'UG', 'status' => 1),
            array('country_name' => 'Ukraine', 'country_code' => 'UA', 'status' => 1),
            array('country_name' => 'United Arab Emirates', 'country_code' => 'AE', 'status' => 1),
            array('country_name' => 'United Kingdom of Great Britain and Northern Ireland', 'country_code' => 'GB', 'status' => 1),
            array('country_name' => 'United Republic of Tanzania', 'country_code' => 'TZ', 'status' => 1),
            array('country_name' => 'Uruguay', 'country_code' => 'UY', 'status' => 1),
            array('country_name' => 'Uzbekistan', 'country_code' => 'UZ', 'status' => 1),
            array('country_name' => 'Vanuatu', 'country_code' => 'VU', 'status' => 1),
            array('country_name' => 'Venezuela (Bolivarian Republic of)', 'country_code' => 'VE', 'status' => 1),
            array('country_name' => 'Viet Nam', 'country_code' => 'VN', 'status' => 1),
            array('country_name' => 'Yemen', 'country_code' => 'YE', 'status' => 1),
            array('country_name' => 'Zambia', 'country_code' => 'ZM', 'status' => 1),
            array('country_name' => 'Zimbabwe', 'country_code' => 'ZW', 'status' => 1),
        );
        DB::table('country_master')->insert($insert_data);
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('country_master');
    }
}
