<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreatePennyErrorCodeMaster extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        // adding new table penny_error_code_master if it not exists
        if(!Schema::hasTable('penny_error_code_master')){
            Schema::create('penny_error_code_master', function (Blueprint $table) {
                $table->id()->comment('Serial ID');
                $table->string('act_code',20)->nullable()->comment('Act Code');
                $table->string('name')->nullable()->comment('Name');
                $table->longText('description')->nullable()->comment('Description');
                $table->longText('scenario')->nullable()->comment('Scenario');
                $table->string('decline_by')->nullable()->comment('Decline by');
                $table->string('payment_response_action')->nullable()->comment('Payment response_action');
                $table->string('status_inquiry_action')->nullable()->comment('Status Inquiry action');
                $table->string('technical_or_bussiness_decline')->nullable()->comment('Technical Decline (TD) / Business Decline (BD)');
                $table->dateTime('created_at')->nullable()->useCurrent()->comment('Created Date');
                $table->dateTime('updated_at')->nullable()->default(DB::raw('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))->comment('Modified Date');

                $table->index('act_code');
                
            });

            $insert_data = array(
                                array('act_code' => '0', 'name' => 'Transaction Successful', 'description' => 'Success', 'scenario' => 'Successful IMPS transaction, where beneficiary is credited in real time', 'decline_by' => '', 'payment_response_action' => 'Success', 'status_inquiry_action' => 'Success', 'technical_or_bussiness_decline' => 'Successful'),
                                array('act_code' => '1', 'name' => 'Transaction Rejected', 'description' => 'Invalid Beneficiary Mobile No / MAS', 'scenario' => 'Beneficiary account number is invalid.', 'decline_by' => 'Beneficiary Bank', 'payment_response_action' => 'Transaction is failed.', 'status_inquiry_action' => 'Transaction is failed.', 'technical_or_bussiness_decline' => 'BD'),
                                array('act_code' => '2', 'name' => 'Transaction Rejected', 'description' => 'Amount limit exceeded for the customer', 'scenario' => 'Exceeds the maximum permissible daily value of transactions', 'decline_by' => 'Beneficiary Bank', 'payment_response_action' => 'Transaction is failed', 'status_inquiry_action' => 'Transaction is failed', 'technical_or_bussiness_decline' => 'BD'),
                                array('act_code' => '3', 'name' => 'Transaction Rejected', 'description' => 'Frozen Account', 'scenario' => 'Beneficiary account is frozen.', 'decline_by' => 'Beneficiary Bank', 'payment_response_action' => 'Transaction is failed', 'status_inquiry_action' => 'Transaction is failed', 'technical_or_bussiness_decline' => 'BD'),
                                array('act_code' => '4', 'name' => 'Transaction Rejected', 'description' => 'NRE Account', 'scenario' => 'Beneficiary account is an NRE account', 'decline_by' => 'Beneficiary Bank', 'payment_response_action' => 'Transaction is failed', 'status_inquiry_action' => 'Transaction is failed', 'technical_or_bussiness_decline' => 'BD'),
                                array('act_code' => '5', 'name' => 'Transaction Rejected', 'description' => 'Closed Account', 'scenario' => 'Beneficiary account is closed', 'decline_by' => 'Beneficiary Bank', 'payment_response_action' => 'Transaction is failed', 'status_inquiry_action' => 'Transaction is failed', 'technical_or_bussiness_decline' => 'BD'),
                                array('act_code' => '6', 'name' => 'Transaction Rejected', 'description' => 'Limit exceeded for member bank', 'scenario' => 'NPCI rejects the transaction because the configured limit is exceeded for the remitter bank in the current settlement cycle.', 'decline_by' => 'NPCI', 'payment_response_action' => 'Transaction is failed', 'status_inquiry_action' => 'Transaction is failed', 'technical_or_bussiness_decline' => 'BD'),
                                array('act_code' => '7', 'name' => 'Transaction Rejected', 'description' => 'Transaction not permitted for this account type', 'scenario' => 'Transaction is not permitted to the particular account type of the beneficiary. e.g. FD Account etc.', 'decline_by' => 'Beneficiary Bank', 'payment_response_action' => 'Transaction is failed', 'status_inquiry_action' => 'Transaction is failed', 'technical_or_bussiness_decline' => 'BD'),
                                array('act_code' => '8', 'name' => 'Transaction Rejected', 'description' => 'Transaction limit exceeded for this account type', 'scenario' => 'Transaction limit set by the beneficiary bank is exceeded', 'decline_by' => 'Beneficiary Bank', 'payment_response_action' => 'Transaction is failed', 'status_inquiry_action' => 'Transaction is failed', 'technical_or_bussiness_decline' => 'BD'),
                                array('act_code' => '9', 'name' => 'Transaction Rejected', 'description' => 'Transaction not allowed as this is non- reloadable card', 'scenario' => 'Transaction is not allowed to a non reloadable card. ', 'decline_by' => 'Beneficiary Bank', 'payment_response_action' => 'Transaction is failed', 'status_inquiry_action' => 'Transaction is failed', 'technical_or_bussiness_decline' => 'BD'),
                                array('act_code' => '10', 'name' => 'Transaction Rejected', 'description' => 'No routing for institution/network', 'scenario' => 'When the IFSC & Bank ID is not configured at ICICI Bank. It can be because the member bank is not yet live at NPCI or it is in a negative list of IFSC.', 'decline_by' => 'Remitter Bank', 'payment_response_action' => 'Transaction is failed', 'status_inquiry_action' => 'Transaction is failed', 'technical_or_bussiness_decline' => 'BD'),
                                array('act_code' => '11', 'name' => 'Time out at NPCI', 'description' => 'Original  transaction  has  been  Timeout –  BC  to  perform  Query  transaction  to check final transaction status', 'scenario' => 'The transaction timed out at NPCI / Beneficiary Bank.', 'decline_by' => 'Not Applicable', 'payment_response_action' => 'Pending', 'status_inquiry_action' => 'Pending (Check 360 status on T+2)', 'technical_or_bussiness_decline' => 'Deemed Approved'),
                                array('act_code' => '12', 'name' => 'Transaction Rejected', 'description' => 'Bank not live on IMPS account / IFSC based fund transfer', 'scenario' => 'Sent by NPCI when the beneficiary bank is not live in IMPS ecosystem.', 'decline_by' => 'NPCI', 'payment_response_action' => 'Transaction is failed', 'status_inquiry_action' => 'Transaction is failed', 'technical_or_bussiness_decline' => 'BD'),
                                array('act_code' => '13', 'name' => 'Transaction Rejected', 'description' => 'Invalid amount', 'scenario' => 'Declined by ICICI Bank API if the amount entered is invalid. It can happen if amount is negative, or < Re.1, or > 5lacs, or contains more than two decimal places.', 'decline_by' => 'Remitter Bank', 'payment_response_action' => 'Transaction is failed', 'status_inquiry_action' => 'Transaction is failed', 'technical_or_bussiness_decline' => 'TD'),
                                array('act_code' => '14', 'name' => 'Transaction Rejected', 'description' => 'Duplicate transaction in IMPS', 'scenario' => 'Declined by ICICI Bank API if a duplicate transaction is initated by the client', 'decline_by' => 'Remitter Bank', 'payment_response_action' => 'Transaction is failed', 'status_inquiry_action' => 'Pending', 'technical_or_bussiness_decline' => 'TD'),
                                array('act_code' => '15', 'name' => 'Transaction Rejected', 'description' => 'Beneficiary is Merchant', 'scenario' => 'Rejected by the beneficiary bank if the beneficiary is a merchant', 'decline_by' => 'Beneficiary Bank', 'payment_response_action' => 'Transaction is failed', 'status_inquiry_action' => 'Transaction is failed', 'technical_or_bussiness_decline' => 'BD'),
                                array('act_code' => '16', 'name' => 'Transaction Rejected / Check Validation Summary to know the reason of invalid input parameter value', 'description' => 'Format Error', 'scenario' => 'Declined by the Remitter bank when there is an error in the format of the packet sent by the client.', 'decline_by' => 'Remitter Bank', 'payment_response_action' => 'Transaction is failed', 'status_inquiry_action' => 'Status inquiry failed.  Reinitiate Status check with correct packet details', 'technical_or_bussiness_decline' => 'TD'),
                                array('act_code' => '17', 'name' => 'Transaction not found', 'description' => 'Financial  P2P/P2A  Transaction  not found.  Initiated  Transactional  Inquiry API after 300 seconds (5 minutes)', 'scenario' => 'The error code is populated by the remitter bank when the transaction is not found.', 'decline_by' => 'Not Applicable', 'payment_response_action' => 'Not Applicable', 'status_inquiry_action' => 'Failed if status check is done after 15 mnts', 'technical_or_bussiness_decline' => 'TD'),
                                array('act_code' => '18', 'name' => 'Transaction Rejected', 'description' => 'NPCI/Issuing bank is not connected or down', 'scenario' => 'NPCI / Beneficiary bank is not connected or is down', 'decline_by' => 'NPCI', 'payment_response_action' => 'Transaction is failed', 'status_inquiry_action' => 'Transaction is failed', 'technical_or_bussiness_decline' => 'TD'),
                                array('act_code' => '19', 'name' => 'Transaction Rejected', 'description' => 'Unconfigured RC', 'scenario' => 'This scenario occours when transaction was declined with an RC which is not configured at the remitter bank', 'decline_by' => '  NPCI / Beneficiary Bank', 'payment_response_action' => 'Transaction is failed', 'status_inquiry_action' => 'Transaction is failed', 'technical_or_bussiness_decline' => 'TD'),
                                array('act_code' => '20', 'name' => 'Transaction Rejected', 'description' => 'Invalid Response Code', 'scenario' => 'Beneficiary bank has declined the transaction with an invalid response code.', 'decline_by' => 'Beneficiary Bank', 'payment_response_action' => 'Transaction is failed', 'status_inquiry_action' => 'Transaction is failed', 'technical_or_bussiness_decline' => 'TD'),
                                array('act_code' => '21', 'name' => 'Transaction Rejected', 'description' => 'Decline on verification', 'scenario' => 'This happens when the orginal request got timed out between the NPCI and the beneficiary bank. On verification, beneficiary bank has declined the transaction.', 'decline_by' => 'Beneficiary Bank', 'payment_response_action' => 'Transaction is failed', 'status_inquiry_action' => 'Transaction is failed', 'technical_or_bussiness_decline' => 'TD'),
                                array('act_code' => '22', 'name' => 'Transaction Rejected', 'description' => 'Transaction not permitted from remitter account', 'scenario' => 'Transaction declined by the remitter bank, which may be due to freeze in the remitter account or if there is an account level concurrency.', 'decline_by' => 'Remitter Bank', 'payment_response_action' => 'Transaction is failed', 'status_inquiry_action' => 'Transaction is failed', 'technical_or_bussiness_decline' => 'BD'),
                                array('act_code' => '24', 'name' => 'Transaction Rejected', 'description' => 'Transaction not allowed - Amount greater then 2 lakh', 'scenario' => 'Transaction is declined by NPCI if the transaction amount is greater than INR 5 lacs', 'decline_by' => 'NPCI', 'payment_response_action' => 'Transaction is failed', 'status_inquiry_action' => 'Transaction is failed', 'technical_or_bussiness_decline' => 'BD'),
                                array('act_code' => '30', 'name' => 'No transaction response from NPCI', 'description' => 'Original  transaction  has  been  Timeout –  BC  to  perform  Query  transaction  to check final transaction status', 'scenario' => 'The transaction timed-out at NPCI', 'decline_by' => 'Not Applicable', 'payment_response_action' => 'Pending', 'status_inquiry_action' => 'Pending (Check 360 status on T+2)', 'technical_or_bussiness_decline' => 'Deemed Approved'),
                                array('act_code' => '31', 'name' => 'No transaction response from CDCI', 'description' => 'Original  transaction  has  been  Timeout –  BC  to  perform  Query  transaction  to check  final  transaction  status.  Kindly check debit account statement.', 'scenario' => 'The transaction got timedout at ICICI Bank CBS', 'decline_by' => 'Not Applicable', 'payment_response_action' => 'Pending', 'status_inquiry_action' => 'Pending', 'technical_or_bussiness_decline' => 'Deemed Approved'),
                                array('act_code' => '32', 'name' => 'Time  out  at  ICICI  CBS  for  outward transaction     (Beneficiary     non-ICICI customer)', 'description' => 'Original  transaction  has  been  Timeout ', 'scenario' => 'Inter-bank transaction timed-out at ICICI Bank CBS', 'decline_by' => 'Remitter Bank', 'payment_response_action' => 'Transaction is failed', 'status_inquiry_action' => 'Transaction is failed', 'technical_or_bussiness_decline' => 'TD'),
                                array('act_code' => '33', 'name' => 'Time   out   at   ICICI   CBS      for   intra transaction         (Beneficiary         ICICI customer)', 'description' => 'Original  transaction  has  been  Timeout –  BC  to  perform  Query  transaction  to check  final  transaction  status.  Kindly check debit account statement.', 'scenario' => 'Intra-bank transaction timed-out at ICICI Bank CBS', 'decline_by' => 'Not Applicable', 'payment_response_action' => 'Pending', 'status_inquiry_action' => 'Pending', 'technical_or_bussiness_decline' => 'Deemed Approved'),
                                array('act_code' => '34', 'name' => 'Transaction Rejected', 'description' => 'Suspect Fraud', 'scenario' => 'NPCI or the beneficiary bank declines the transaction if they suspect that there is a fraud', 'decline_by' => 'NPCI / Beneficiary Bank', 'payment_response_action' => 'Transaction is failed', 'status_inquiry_action' => 'Transaction is failed', 'technical_or_bussiness_decline' => 'BD'),
                                array('act_code' => '35', 'name' => 'Transaction Rejected', 'description' => 'Invalid Message', 'scenario' => 'Technical decline by beneficiary bank due to transaction processing problem.', 'decline_by' => 'Beneficiary Bank', 'payment_response_action' => 'Transaction is failed', 'status_inquiry_action' => 'Transaction is failed', 'technical_or_bussiness_decline' => 'TD'),
                                array('act_code' => '36', 'name' => 'Transaction Rejected', 'description' => 'Invalid Transaction', 'scenario' => 'Technical decline by beneficiary bank due to transaction processing problem.', 'decline_by' => 'Beneficiary Bank', 'payment_response_action' => 'Transaction is failed', 'status_inquiry_action' => 'Transaction is failed', 'technical_or_bussiness_decline' => 'TD'),
                                array('act_code' => '37', 'name' => 'Transaction Rejected', 'description' => 'Invalid Amount', 'scenario' => 'Technical decline by beneficiary bank due to transaction processing problem.', 'decline_by' => 'Beneficiary Bank', 'payment_response_action' => 'Transaction is failed', 'status_inquiry_action' => 'Transaction is failed', 'technical_or_bussiness_decline' => 'TD'),
                                array('act_code' => '38', 'name' => 'Transaction Rejected', 'description' => 'Transfer amount exceeds limit', 'scenario' => 'Exceeds the maximum permissible per transaction value', 'decline_by' => 'Beneficiary Bank', 'payment_response_action' => 'Transaction is failed', 'status_inquiry_action' => 'Transaction is failed', 'technical_or_bussiness_decline' => 'BD'),
                                array('act_code' => '39', 'name' => 'Transaction Rejected', 'description' => 'Time out at CDCI for outward transaction', 'scenario' => 'Timeout at CDCI for outward transaction', 'decline_by' => 'Not Applicable', 'payment_response_action' => 'Transaction is failed', 'status_inquiry_action' => 'Transaction is failed', 'technical_or_bussiness_decline' => 'TD'),
                                array('act_code' => '40', 'name' => 'Transaction Rejected', 'description' => 'Time out at CDCI for intra-bank transaction', 'scenario' => 'Timeout at CDCI for intra-bank transaction', 'decline_by' => 'Not Applicable', 'payment_response_action' => 'Pending', 'status_inquiry_action' => 'Pending', 'technical_or_bussiness_decline' => 'NA'),
                                array('act_code' => '41', 'name' => 'Transaction Rejected', 'description' => 'Transaction not processed as client txn date expired', 'scenario' => 'If the txn date/ time mentioned in the API request is not equal to current date/time, or it is not in the format YYYYMMDDHHmmss.', 'decline_by' => 'Remitter Bank', 'payment_response_action' => 'Transaction is failed', 'status_inquiry_action' => 'Transaction is failed', 'technical_or_bussiness_decline' => 'TD'),
                                array('act_code' => '51', 'name' => 'Transaction Rejected', 'description' => 'Transaction declined by beneficiary bank due to insufficient funds', 'scenario' => 'Transaction is declined by the beneficiary bank due to insufficient funds in their pool account.', 'decline_by' => 'Beneficiary Bank', 'payment_response_action' => 'Transaction is failed', 'status_inquiry_action' => 'Transaction is failed', 'technical_or_bussiness_decline' => 'BD'),
                                array('act_code' => '52', 'name' => 'Transaction Rejected', 'description' => 'Invalid Account', 'scenario' => 'Beneficiary account is invalid', 'decline_by' => 'Beneficiary Bank', 'payment_response_action' => 'Transaction is failed', 'status_inquiry_action' => 'Transaction is failed', 'technical_or_bussiness_decline' => 'BD'),
                                array('act_code' => '60', 'name' => 'Transaction Rejected', 'description' => 'Reason Unknown (Technical decline by IMPS)', 'scenario' => 'Transaction declined due to a technical issue.', 'decline_by' => 'Remitter Bank', 'payment_response_action' => 'Transaction is failed', 'status_inquiry_action' => 'Pending', 'technical_or_bussiness_decline' => 'TD'),
                                array('act_code' => '61', 'name' => 'Transaction Rejected', 'description' => 'Reason Unknown (Technical decline by CBS)', 'scenario' => 'Transaction declined due to a technical issue.', 'decline_by' => 'Remitter Bank', 'payment_response_action' => 'Transaction is failed', 'status_inquiry_action' => 'Pending', 'technical_or_bussiness_decline' => 'TD'),
                                array('act_code' => '62', 'name' => 'Transaction Rejected', 'description' => 'Reason Unknown (Technical decline by NPCI)', 'scenario' => 'Undefined response code sent by NPCI.', 'decline_by' => 'NPCI', 'payment_response_action' => 'Transaction is failed', 'status_inquiry_action' => 'Transaction is failed', 'technical_or_bussiness_decline' => 'TD'),
                                array('act_code' => '63', 'name' => 'No response from IMPS switch', 'description' => 'Original  transaction  has  been  Timeout –  BC  to  perform  Query  transaction  to check final transaction status.', 'scenario' => 'Transaction timed-out at ICICI Bank.', 'decline_by' => 'Not Applicable', 'payment_response_action' => 'Pending', 'status_inquiry_action' => 'Pending', 'technical_or_bussiness_decline' => 'NA'),
                                array('act_code' => '65', 'name' => 'Transaction Rejected', 'description' => 'Exceed Account limit', 'scenario' => 'Daily limit (count) of transactions in the beneficiary account has been breached.  OR,  Exceeds the maximum permissible balance in the account of the beneficiary. (e.g. Jan Dhan Yojana accounts, Payments Bank etc.) ', 'decline_by' => 'Beneficiary Bank', 'payment_response_action' => 'Transaction is failed', 'status_inquiry_action' => 'Transaction is failed', 'technical_or_bussiness_decline' => 'BD'),
                                array('act_code' => '67', 'name' => 'Transaction Rejected', 'description' => 'Customer reversed', 'scenario' => 'Funds returned by beneficiary bank. ', 'decline_by' => 'Beneficiary Bank', 'payment_response_action' => 'Not Applicable', 'status_inquiry_action' => 'Transaction is failed', 'technical_or_bussiness_decline' => 'TD'),
                                array('act_code' => '70', 'name' => 'Transaction Rejected', 'description' => 'OCH - Technical Failure', 'scenario' => 'Technical failure at OCH.', 'decline_by' => 'Remitter Bank', 'payment_response_action' => 'Transaction is failed', 'status_inquiry_action' => 'Transaction is failed', 'technical_or_bussiness_decline' => 'TD'),
                                array('act_code' => '71', 'name' => 'Transaction Rejected', 'description' => 'OCH – Invalid Amount', 'scenario' => 'Technical failure at OCH.', 'decline_by' => 'Remitter Bank', 'payment_response_action' => 'Transaction is failed', 'status_inquiry_action' => 'Transaction is failed', 'technical_or_bussiness_decline' => 'TD'),
                                array('act_code' => '72', 'name' => 'Transaction Rejected', 'description' => 'OCH Invalid account number', 'scenario' => 'Technical failure at OCH.', 'decline_by' => 'Remitter Bank', 'payment_response_action' => 'Transaction is failed', 'status_inquiry_action' => 'Transaction is failed', 'technical_or_bussiness_decline' => 'TD'),
                                array('act_code' => '73', 'name' => 'OCH Timeout', 'description' => 'Original transaction has been Timeout – BC to check final status of transaction after RECON', 'scenario' => 'Timeout at OCH', 'decline_by' => 'Remitter Bank', 'payment_response_action' => 'Transaction is failed', 'status_inquiry_action' => 'Transaction is failed', 'technical_or_bussiness_decline' => 'TD'),
                                array('act_code' => '74', 'name' => 'OCH Batch limit has been exhausted', 'description' => 'BC to credit amount in current or nodal account to avoid uninterrupted service', 'scenario' => 'Transactions are declined for OCH. Client need to ensure funds are available in current or nodal account.', 'decline_by' => 'Remitter Bank', 'payment_response_action' => 'Transaction is failed', 'status_inquiry_action' => 'Transaction is failed', 'technical_or_bussiness_decline' => 'TD'),
                                array('act_code' => '75', 'name' => 'Transaction Rejected', 'description' => 'Duplicate transaction in OCH', 'scenario' => 'Technical failure at OCH.', 'decline_by' => 'Remitter Bank', 'payment_response_action' => 'Transaction is failed', 'status_inquiry_action' => 'Transaction is failed', 'technical_or_bussiness_decline' => 'TD'),
                                array('act_code' => '76', 'name' => 'OCH defined limit decreased and transaction decline', 'description' => 'BC to credit amount in current or nodal account to avoid uninterrupted service', 'scenario' => 'Balance not available in remitter\'s account.', 'decline_by' => 'Remitter Bank', 'payment_response_action' => 'Transaction is failed', 'status_inquiry_action' => 'Transaction is failed', 'technical_or_bussiness_decline' => 'BD'),
                                array('act_code' => '77', 'name' => 'Transaction Rejected', 'description' => 'Balance Inquiry has been decined due to technical error', 'scenario' => 'Technical failure at OCH.', 'decline_by' => 'Remitter Bank', 'payment_response_action' => 'Transaction is failed', 'status_inquiry_action' => 'Transaction is failed', 'technical_or_bussiness_decline' => 'TD'),
                                array('act_code' => '80', 'name' => 'Initial request is already been processed', 'description' => 'Duplicate transaction request received from the client (Omit processing). – BC to perform Query transaction to check final transaction status', 'scenario' => 'The error is populated by the remitter bank if the same request initiated almost instantly before the first transaction is logged in the system', 'decline_by' => 'Remitter Bank', 'payment_response_action' => 'Pending', 'status_inquiry_action' => 'Pending', 'technical_or_bussiness_decline' => 'TD'),
                                array('act_code' => '96', 'name' => 'Transaction Rejected', 'description' => 'Unable to process', 'scenario' => 'Technical decline by beneficiary bank due to transaction processing problem.', 'decline_by' => 'Beneficiary Bank', 'payment_response_action' => 'Transaction is failed', 'status_inquiry_action' => 'Pending', 'technical_or_bussiness_decline' => 'TD'),
                                array('act_code' => '101', 'name' => 'Transaction Rejected', 'description' => 'IMPS Switch Not reachable', 'scenario' => 'IMPS Switch Not reachable', 'decline_by' => 'Remitter Bank', 'payment_response_action' => 'Transaction is failed', 'status_inquiry_action' => 'Pending', 'technical_or_bussiness_decline' => 'TD'),
                                array('act_code' => '102', 'name' => 'Connectivity disconnected, transaction in processing mode.', 'description' => 'BC to perform Query transaction to check final transaction status', 'scenario' => 'Connectivity is disconnected while the transaction is in process.', 'decline_by' => 'Not Applicable', 'payment_response_action' => 'Pending', 'status_inquiry_action' => 'Pending', 'technical_or_bussiness_decline' => 'Not Applicable'),
                                array('act_code' => '201', 'name' => 'Transaction Rejected', 'description' => 'Invalid Beneficiary IFSC Code or NBIN', 'scenario' => 'When the beneficiary IFSC code is invalid, the transaction is rejected by NPCI', 'decline_by' => 'NPCI', 'payment_response_action' => 'Transaction is failed', 'status_inquiry_action' => 'Transaction is failed', 'technical_or_bussiness_decline' => 'BD'),
                                array('act_code' => '202', 'name' => 'Transaction Rejected', 'description' => 'Customer Limit Exceeded', 'scenario' => 'Customer transaction Limit Exceeded', 'decline_by' => 'Beneficiary Bank', 'payment_response_action' => 'Transaction is failed', 'status_inquiry_action' => 'Transaction is failed', 'technical_or_bussiness_decline' => 'BD'),
                                array('act_code' => '203', 'name' => 'Transaction Rejected', 'description' => 'Foreign inward remittance not allowed', 'scenario' => 'Not Applicable for Composite Payouts', 'decline_by' => '', 'payment_response_action' => 'Transaction is failed', 'status_inquiry_action' => 'Transaction is failed', 'technical_or_bussiness_decline' => 'BD'),
                                array('act_code' => '204', 'name' => 'Transaction Rejected', 'description' => 'Transaction not allowed as invalid payment reference', 'scenario' => 'Decline by NPCI / Beneficiary Bank', 'decline_by' => 'NPCI / Beneficiary Bank', 'payment_response_action' => 'Transaction is failed', 'status_inquiry_action' => 'Transaction is failed', 'technical_or_bussiness_decline' => 'BD'),
                                array('act_code' => '205', 'name' => 'Transaction Rejected', 'description' => 'Transaction amount less then Rs.1', 'scenario' => 'Transaction is declined by NPCI if the payment amount is less than INR 1.00', 'decline_by' => 'NPCI', 'payment_response_action' => 'Transaction is failed', 'status_inquiry_action' => 'Transaction is failed', 'technical_or_bussiness_decline' => 'BD'),
                                array('act_code' => '206', 'name' => 'Transaction Rejected', 'description' => 'Transaction not allowed as invalid remitter account', 'scenario' => 'Transaction is declined by beneficiary bank due to invalid remitter account number', 'decline_by' => 'Beneficiary Bank', 'payment_response_action' => 'Transaction is failed', 'status_inquiry_action' => 'Transaction is failed', 'technical_or_bussiness_decline' => 'BD'),
                                array('act_code' => '207', 'name' => 'Transaction Rejected', 'description' => 'Transaction not allowed as general error', 'scenario' => 'General error', 'decline_by' => 'NPCI', 'payment_response_action' => 'Transaction is failed', 'status_inquiry_action' => 'Transaction is failed', 'technical_or_bussiness_decline' => 'BD'),
                                array('act_code' => '208', 'name' => 'Transaction Rejected', 'description' => 'Foreign inward remittance for P2P only', 'scenario' => 'Not Applicable for Composite Payouts', 'decline_by' => '', 'payment_response_action' => 'Transaction is failed', 'status_inquiry_action' => 'Transaction is failed', 'technical_or_bussiness_decline' => 'BD'),
                                array('act_code' => '403', 'name' => 'Transaction Rejected', 'description' => 'Unauthorized API Access', 'scenario' => 'Transaction initiated from unwhitelisted IP.', 'decline_by' => 'Remitter Bank', 'payment_response_action' => 'Transaction is failed', 'status_inquiry_action' => 'Pending', 'technical_or_bussiness_decline' => 'TD'),
                                array('act_code' => '901', 'name' => 'Transaction Rejected', 'description' => 'Invalid BC', 'scenario' => 'Declined by remitter bank for invalid BC details', 'decline_by' => 'Remitter Bank', 'payment_response_action' => 'Transaction is failed', 'status_inquiry_action' => 'Pending', 'technical_or_bussiness_decline' => 'TD'),
                                array('act_code' => '902', 'name' => 'Transaction Rejected', 'description' => 'Authentication failed', 'scenario' => 'Declined by remitter bank if the passcode is incorrect.', 'decline_by' => 'Remitter Bank', 'payment_response_action' => 'Transaction is failed', 'status_inquiry_action' => 'Pending', 'technical_or_bussiness_decline' => 'TD'),
                                array('act_code' => '903', 'name' => 'Transaction Rejected', 'description' => 'Invalid BC Retailer', 'scenario' => 'Declined by remitter bank for invalid BC retailer code.', 'decline_by' => 'Remitter Bank', 'payment_response_action' => 'Transaction is failed', 'status_inquiry_action' => 'Transaction is failed', 'technical_or_bussiness_decline' => 'TD'),
                                array('act_code' => '904', 'name' => 'Transaction Rejected', 'description' => 'No response from DCMS', 'scenario' => 'Declined by remitter bank for an internal exception', 'decline_by' => 'Remitter Bank', 'payment_response_action' => 'Transaction is failed', 'status_inquiry_action' => 'Transaction is failed', 'technical_or_bussiness_decline' => 'TD'),
                                array('act_code' => '905', 'name' => 'Transaction Rejected', 'description' => 'Card Validation failed', 'scenario' => 'Declined by the Remitter bank if the card validation has failed', 'decline_by' => 'Remitter Bank', 'payment_response_action' => 'Transaction is failed', 'status_inquiry_action' => 'Transaction is failed', 'technical_or_bussiness_decline' => 'TD'),
                                array('act_code' => '915', 'name' => 'Transaction Rejected', 'description' => 'BC Nodal Account not supported', 'scenario' => 'Not Applicable for Composite Payouts', 'decline_by' => '', 'payment_response_action' => 'Transaction is failed', 'status_inquiry_action' => 'Transaction is failed', 'technical_or_bussiness_decline' => 'TD'),
                                array('act_code' => '916', 'name' => 'Transaction Rejected', 'description' => 'BC Nodal Account not Found', 'scenario' => 'Not Applicable for Composite Payouts', 'decline_by' => '', 'payment_response_action' => 'Transaction is failed', 'status_inquiry_action' => 'Transaction is failed', 'technical_or_bussiness_decline' => 'TD'),
                                array('act_code' => '917', 'name' => 'Transaction Rejected', 'description' => 'BC Retailer code mapping not Found', 'scenario' => 'Not Applicable for Composite Payouts', 'decline_by' => '', 'payment_response_action' => 'Transaction is failed', 'status_inquiry_action' => 'Transaction is failed', 'technical_or_bussiness_decline' => 'TD'),
                                array('act_code' => '918', 'name' => 'Transaction Rejected', 'description' => 'BC daily amount high', 'scenario' => 'Not Applicable for Composite Payouts', 'decline_by' => '', 'payment_response_action' => 'Transaction is failed', 'status_inquiry_action' => 'Transaction is failed', 'technical_or_bussiness_decline' => 'TD'),
                                array('act_code' => '919', 'name' => 'Transaction Rejected', 'description' => 'BC monthly amount high', 'scenario' => 'Not Applicable for Composite Payouts', 'decline_by' => '', 'payment_response_action' => 'Transaction is failed', 'status_inquiry_action' => 'Transaction is failed', 'technical_or_bussiness_decline' => 'TD'),
                                array('act_code' => '920', 'name' => 'Transaction Rejected', 'description' => 'BC min invalid amount', 'scenario' => 'Not Applicable for Composite Payouts', 'decline_by' => '', 'payment_response_action' => 'Transaction is failed', 'status_inquiry_action' => 'Transaction is failed', 'technical_or_bussiness_decline' => 'TD'),
                                array('act_code' => '921', 'name' => 'Transaction Rejected', 'description' => 'BC max invalid amount', 'scenario' => 'Not Applicable for Composite Payouts', 'decline_by' => '', 'payment_response_action' => 'Transaction is failed', 'status_inquiry_action' => 'Transaction is failed', 'technical_or_bussiness_decline' => 'TD'),
                                array('act_code' => '922', 'name' => 'Transaction Rejected', 'description' => 'Channel GST amount missing', 'scenario' => 'Not Applicable for Composite Payouts', 'decline_by' => '', 'payment_response_action' => 'Transaction is failed', 'status_inquiry_action' => 'Transaction is failed', 'technical_or_bussiness_decline' => 'TD'),
                                array('act_code' => '923', 'name' => 'Transaction Rejected', 'description' => 'Channel service charge amount missing', 'scenario' => 'Not Applicable for Composite Payouts', 'decline_by' => '', 'payment_response_action' => 'Transaction is failed', 'status_inquiry_action' => 'Transaction is failed', 'technical_or_bussiness_decline' => 'TD'),
                                array('act_code' => '924', 'name' => 'Transaction Rejected', 'description' => 'Channel retailer state missing', 'scenario' => 'Not Applicable for Composite Payouts', 'decline_by' => '', 'payment_response_action' => 'Transaction is failed', 'status_inquiry_action' => 'Transaction is failed', 'technical_or_bussiness_decline' => 'TD'),
                                array('act_code' => '68', 'name' => 'Transaction Rejected', 'description' => 'Duplicate transaction with settlement ID', 'scenario' => 'The transaction is rejected with this error code if there already exists a transaction with the same Settlement ID which is PENDING or is SUCCESSFUL. Applicable for clients who are configured for sending this parameter.', 'decline_by' => 'Remitter Bank', 'payment_response_action' => 'Transaction is failed', 'status_inquiry_action' => 'Transaction is failed', 'technical_or_bussiness_decline' => 'BD'),
                                array('act_code' => '69', 'name' => 'Transaction Rejected', 'description' => 'Funds returned from beneficiary bank', 'scenario' => 'The response code is populated in status check API if the funds are returned from the beneficiary bank', 'decline_by' => 'Beneficiary Bank', 'payment_response_action' => 'Not Applicable', 'status_inquiry_action' => 'Transaction is failed', 'technical_or_bussiness_decline' => 'BD'),
                                array('act_code' => '50', 'name' => 'Transaction Pending', 'description' => 'CHECK TRANSACTION LIMIT EXCEEDED', 'scenario' => 'This response is populated by NPCI if the limit for number of check transactions is breached', 'decline_by' => 'NPCI', 'payment_response_action' => 'Not Applicable', 'status_inquiry_action' => 'Pending (Check 360 status on T+2)', 'technical_or_bussiness_decline' => 'BD'),
                                array('act_code' => '29', 'name' => 'Transaction Rejected', 'description' => 'SUSPECTED FRAUD, DECLINE TRANSACTIONS DECLINED BASIS RISK SCORE', 'scenario' => 'This response is populated by NPCI for suspected fraud basis the risk score', 'decline_by' => 'NPCI', 'payment_response_action' => 'Transaction is failed', 'status_inquiry_action' => 'Transaction is failed', 'technical_or_bussiness_decline' => 'BD'),
                                array('act_code' => '49', 'name' => 'Transaction Rejected', 'description' => 'SUSPECTED FRAUD, DECLINE TRANSACTIONS DECLINED BASED ON MODEL RISK SCORE', 'scenario' => 'This response is populated by NPCI for suspected fraud basis the model risk score', 'decline_by' => 'NPCI', 'payment_response_action' => 'Transaction is failed', 'status_inquiry_action' => 'Transaction is failed', 'technical_or_bussiness_decline' => 'BD'),
                                array('act_code' => 'U01', 'name' => 'Transaction Rejected', 'description' => 'The request is duplicate', 'scenario' => 'The response code is populated by NPCI for a duplicate request', 'decline_by' => 'NPCI', 'payment_response_action' => 'Transaction is failed', 'status_inquiry_action' => 'Transaction is failed', 'technical_or_bussiness_decline' => 'TD'),
                                array('act_code' => 'U02', 'name' => 'Transaction Rejected', 'description' => 'Amount CAP is exceeded', 'scenario' => 'The response code is populated by NPCI if the amount cap is exceeded', 'decline_by' => 'NPCI', 'payment_response_action' => 'Transaction is failed', 'status_inquiry_action' => 'Transaction is failed', 'technical_or_bussiness_decline' => 'BD'),
                                array('act_code' => 'U03', 'name' => 'Transaction Rejected', 'description' => 'Net debit CAP is exceeded', 'scenario' => 'The response code is populated by NPCI if the net debit cap is exceeded', 'decline_by' => 'NPCI', 'payment_response_action' => 'Transaction is failed', 'status_inquiry_action' => 'Transaction is failed', 'technical_or_bussiness_decline' => 'BD'),
                                array('act_code' => 'U04', 'name' => 'Transaction Rejected', 'description' => 'Request is not found', 'scenario' => 'The response code is populated by NPCI if the request is not found', 'decline_by' => 'NPCI', 'payment_response_action' => 'Transaction is failed', 'status_inquiry_action' => 'Transaction is failed', 'technical_or_bussiness_decline' => 'TD'),
                                array('act_code' => 'U06', 'name' => 'Transaction Rejected', 'description' => 'Transaction ID is mismatched', 'scenario' => 'The response code is populated by NPCI if there is a mismatch in the transaction ID', 'decline_by' => 'NPCI', 'payment_response_action' => 'Transaction is failed', 'status_inquiry_action' => 'Transaction is failed', 'technical_or_bussiness_decline' => 'TD'),
                                array('act_code' => 'U17', 'name' => 'Transaction Rejected', 'description' => 'Beneficiary is not registered', 'scenario' => 'The response code is populated by NPCI if the beneficiary bank is not registered', 'decline_by' => 'NPCI', 'payment_response_action' => 'Transaction is failed', 'status_inquiry_action' => 'Transaction is failed', 'technical_or_bussiness_decline' => 'BD'),
                                array('act_code' => 'U28', 'name' => 'Transaction Rejected', 'description' => 'Beneficiary not available', 'scenario' => 'The response code is populated by NPCI if the beneficiary bank is not available', 'decline_by' => 'NPCI', 'payment_response_action' => 'Transaction is failed', 'status_inquiry_action' => 'Transaction is failed', 'technical_or_bussiness_decline' => 'TD'),
                                array('act_code' => 'U48', 'name' => 'Transaction Rejected', 'description' => 'Transaction id is not present', 'scenario' => 'The response code is populated by NPCI if the transaction id is not present', 'decline_by' => 'NPCI', 'payment_response_action' => 'Transaction is failed', 'status_inquiry_action' => 'Transaction is failed', 'technical_or_bussiness_decline' => 'TD'),
                                array('act_code' => 'U49', 'name' => 'Transaction Rejected', 'description' => 'Request message id is not present', 'scenario' => 'The response code is populated by NPCI if the request message id is not present', 'decline_by' => 'NPCI', 'payment_response_action' => 'Transaction is failed', 'status_inquiry_action' => 'Transaction is failed', 'technical_or_bussiness_decline' => 'TD'),
                                array('act_code' => 'U52', 'name' => 'Transaction Rejected', 'description' => 'Beneficiary orgId not found', 'scenario' => 'The response code is populated by NPCI if the beneficiary orgID is not found in the request', 'decline_by' => 'NPCI', 'payment_response_action' => 'Transaction is failed', 'status_inquiry_action' => 'Transaction is failed', 'technical_or_bussiness_decline' => 'TD'),
                );

            DB::table('penny_error_code_master')->insert($insert_data);
        }
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('penny_error_code_master');
    }
}
